services:
  proxy:
    image: nginx:1.28-alpine
    ports:
      - "8080:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api
    networks:
      - public
      - backend

  frontend:
    image: nginx:1.28-alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - public
      - backend

  api:
    build: ./api
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    networks:
      - backend
      - data

  worker:
    build: ./worker
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    networks:
      - data

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - data

  redis:
    image: redis:7-alpine
    networks:
      - data

volumes:
  postgres_data:

networks:
  public:
  backend:
  data:
